import { useCallback, useEffect, useState } from 'react';
import type { FormEvent } from 'react';

import { getApiErrorMessage } from '../lib/auth-api';
import { auditRequest, replaceScopesRequest, scopesRequest } from '../lib/administration-api';
import type { AuditItem, StaffScope } from '../lib/administration-api';
import { catalogRequest } from '../lib/master-data-api';
import { usersRequest } from '../lib/users-api';
import type { MasterCatalog } from '../types/master-data';
import type { UserProfile } from '../types/users';

function value(data:FormData,name:string):string{const entry=data.get(name);return typeof entry==='string'?entry.trim():'';}
function date(value:string):string{return new Intl.DateTimeFormat('en-PK',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
export function AdministrationPage(){
  const [audit,setAudit]=useState<AuditItem[]>([]);const [scopes,setScopes]=useState<StaffScope[]>([]);
  const [staff,setStaff]=useState<UserProfile[]>([]);const [catalog,setCatalog]=useState<MasterCatalog|null>(null);const [search,setSearch]=useState('');
  const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const [l,s,u,c]=await Promise.all([auditRequest(1,search),scopesRequest(),usersRequest({params:{pageSize:100}}),catalogRequest()]);setAudit(l.items);setScopes(s);setStaff(u.items.filter((item)=>item.role==='technician'||item.role==='supervisor'));setCatalog(c);setError(null);}catch(caught){setError(getApiErrorMessage(caught));}},[search]);
  useEffect(()=>{void load();},[load]);
  const replaceScope=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);try{const userId=Number(value(data,'userId'));const domain=value(data,'domain') as 'consumer'|'employee';await replaceScopesRequest(userId,[{domain,...(value(data,'departmentId')===''?{}:{departmentId:Number(value(data,'departmentId'))}),...(value(data,'categoryId')===''?{}:{categoryId:Number(value(data,'categoryId'))}),...(value(data,'circleId')===''?{}:{circleId:Number(value(data,'circleId'))}),canSelfAssign:data.get('canSelfAssign')==='on'}]);setMessage('Routing scope replaced.');await load();}catch(caught){setError(getApiErrorMessage(caught));}finally{setBusy(false);}};
  return <main className="workspace-page"><div className="workspace-page__heading"><div><p>Administration / governance</p><h1>Operations controls</h1></div></div>{(error!==null||message!==null)&&<p className={error===null?'page-message is-success':'page-message is-error'}>{error??message}</p>}
    <div className="admin-ops-grid"><form className="panel admin-ops-card" onSubmit={(event)=>void replaceScope(event)}><div className="panel__heading"><div><span>Routing</span><h2>Replace staff scope</h2></div></div><label><span>Staff member</span><select name="userId" required><option value="">Select staff</option>{staff.map((item)=><option key={item.id} value={item.id}>{item.displayName} · {item.role}</option>)}</select></label><label><span>Domain</span><select name="domain"><option value="consumer">Consumer</option><option value="employee">Employee</option></select></label><label><span>Department (optional)</span><select name="departmentId"><option value="">All departments</option>{catalog?.departments.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Category (optional)</span><select name="categoryId"><option value="">All categories</option>{catalog?.categories.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Circle (optional)</span><select name="circleId"><option value="">All circles</option>{catalog?.circles.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="check-row"><input name="canSelfAssign" type="checkbox"/><span>May self-assign</span></label><button className="button button--secondary" disabled={busy} type="submit">Replace scope</button></form></div>
    <section className="panel admin-data-panel"><div className="panel__heading"><div><span>Access boundaries</span><h2>Staff scopes</h2></div></div>{scopes.map((item)=><article className="admin-list-row" key={item.id}><div><strong>{item.displayName} · {item.domain}</strong><p>{item.departmentName??item.categoryName??item.circleName??'All matching tickets'}</p></div><span>{item.canSelfAssign?'Self-assign':'Managed assignment'}</span></article>)}</section>
    <section className="panel admin-data-panel"><div className="panel__heading"><div><span>Immutable evidence</span><h2>Audit log</h2></div><form onSubmit={(event)=>{event.preventDefault();setSearch(value(new FormData(event.currentTarget),'search'));}}><input name="search" placeholder="Action, entity, or actor"/><button type="submit">Search</button></form></div>{audit.map((item)=><article className="audit-row" key={item.id}><code>{item.action}</code><span>{item.actorName??'System'} · {item.entityType} #{item.entityId??'—'}</span><time>{date(item.createdAt)}</time><strong>{item.result}</strong></article>)}</section>
  </main>;
}
